# Generated by Django 2.2.10 on 2020-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default='NULL', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default='NULL', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='NULL', upload_to='images/'),
        ),
    ]
