# Generated by Django 2.2.10 on 2020-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200614_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default='t', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default='NUtL', upload_to='images/'),
        ),
    ]
